"""Synthetic seed: one JSON source, two consumers.

* load_seed()  loads supabase/seed_data.json into the fake PostgREST.
* build_sql()  renders the same data as supabase/seed.sql for real Postgres.

Dates in the JSON are offsets in days from "today", so there are always overdue next
steps whatever day the demo runs. Every name, phone, email and URL is invented:
emails and websites use example.com, phones use the Ofcom range reserved for drama
(+44 7700 900xxx), because Spain has no officially fictitious range.
"""

from __future__ import annotations

import json
from collections.abc import Mapping
from datetime import UTC, date, datetime, timedelta
from pathlib import Path
from typing import Any

ROOT = Path(__file__).resolve().parents[1]
SEED_JSON = ROOT / "supabase" / "seed_data.json"
SEED_SQL = ROOT / "supabase" / "seed.sql"

PROSPECT_FIELDS = (
    "nombre",
    "ciudad",
    "telefono",
    "email",
    "web",
    "score",
    "tamano",
    "hallazgos",
    "propuesta",
    "canal",
    "origen",
    "estado",
    "resultado",
    "motivo_cierre",
    "proximo_paso",
    "valor_cents",
)


def prospect_id(index: int) -> str:
    return f"00000000-0000-4000-8000-{index:012d}"


def read_seed(path: str | Path = SEED_JSON) -> dict[str, Any]:
    data: dict[str, Any] = json.loads(Path(path).read_text(encoding="utf-8"))
    return data


def _offset(days: int | None, today: date) -> str | None:
    return None if days is None else (today + timedelta(days=days)).isoformat()


def load_seed(fake: Any, path: str | Path = SEED_JSON, today: date | None = None) -> None:
    today = today or date.today()
    data = read_seed(path)
    stamp = datetime.now(UTC).isoformat(timespec="seconds")
    for i, raw in enumerate(data["prospectos"], start=1):
        row = {f: raw.get(f) for f in PROSPECT_FIELDS}
        row.update(
            id=prospect_id(i),
            ciudad=row["ciudad"] or "",
            telefono=row["telefono"] or "",
            email=row["email"] or "",
            web=row["web"] or "",
            tamano=row["tamano"] or "",
            propuesta=row["propuesta"] or "",
            canal=row["canal"] or "",
            origen=row["origen"] or "manual",
            motivo_cierre=row["motivo_cierre"] or "",
            proximo_paso=row["proximo_paso"] or "",
            hallazgos=row["hallazgos"] or [],
            valor_cents=row["valor_cents"] or 0,
            proxima_fecha=_offset(raw.get("proxima_fecha_dias"), today),
            fecha_ultimo_contacto=_offset(raw.get("fecha_ultimo_contacto_dias"), today),
            creado_en=stamp,
            actualizado_en=stamp,
        )
        fake.tables["prospectos"].append(row)
        fake.audit(row["id"], row["nombre"], "INSERT", rol="postgres", actor=None)
    for event in data.get("historial", []):
        pid = prospect_id(event["prospecto"])
        rol, actor = (
            ("crm_agent", event["actor"]) if event["como"] == "agente" else ("postgres", None)
        )
        if event["tipo"] == "update":
            row = next(p for p in fake.tables["prospectos"] if p["id"] == pid)
            changes = dict(event["cambios"])
            for key in list(changes):
                if key.endswith("_dias"):
                    changes[key[: -len("_dias")]] = _offset(changes.pop(key), today)
            fake.apply_update(row, changes, rol, actor)
        else:
            autor = f"agente:{actor}" if event["como"] == "agente" else event["autor"]
            fake.add_note(pid, event["cuerpo"], autor, rol, actor)


def _lit(value: Any) -> str:
    if value is None:
        return "null"
    if isinstance(value, bool):
        return "true" if value else "false"
    if isinstance(value, int):
        return str(value)
    if isinstance(value, list | dict):
        return _lit(json.dumps(value, ensure_ascii=False)) + "::jsonb"
    return "'" + str(value).replace("'", "''") + "'"


def _date_expr(days: int | None) -> str:
    if days is None:
        return "null"
    return f"current_date + {days}" if days >= 0 else f"current_date - {-days}"


def _assignments(changes: Mapping[str, Any]) -> str:
    parts = []
    for key, value in changes.items():
        if key.endswith("_dias"):
            parts.append(f"{key[: -len('_dias')]} = {_date_expr(value)}")
        else:
            parts.append(f"{key} = {_lit(value)}")
    return ", ".join(parts)


def build_sql(data: Mapping[str, Any]) -> str:
    out = [
        "-- GENERATED by `python -m devtools.seed` from supabase/seed_data.json. Do not edit.",
        "-- Synthetic data only: invented firms, example.com addresses, Ofcom drama-range phones.",
        "-- Run after migrations, as the table owner (supabase db reset does this).",
        "",
        "begin;",
        "",
    ]
    cols = ("id", *PROSPECT_FIELDS, "proxima_fecha", "fecha_ultimo_contacto")
    out.append(f"insert into public.prospectos ({', '.join(cols)}) values")
    values = []
    for i, raw in enumerate(data["prospectos"], start=1):
        row = [_lit(prospect_id(i))]
        for field in PROSPECT_FIELDS:
            value = raw.get(field)
            if value is None and field not in ("resultado",):
                value = {"score": 0, "valor_cents": 0, "hallazgos": [], "origen": "manual"}.get(
                    field, ""
                )
            row.append(_lit(value))
        row.append(_date_expr(raw.get("proxima_fecha_dias")))
        row.append(_date_expr(raw.get("fecha_ultimo_contacto_dias")))
        values.append("  (" + ", ".join(row) + ")")
    out.append(",\n".join(values) + ";")
    out.append("")
    for event in data.get("historial", []):
        pid = _lit(prospect_id(event["prospecto"]))
        out.append(f"-- {event['descripcion']}")
        if event["como"] == "agente":
            claims = json.dumps({"role": "crm_agent", "actor": event["actor"]})
            out.append("set local role crm_agent;")
            out.append(f"select set_config('request.jwt.claims', {_lit(claims)}, true);")
        if event["tipo"] == "update":
            out.append(
                f"update public.prospectos set {_assignments(event['cambios'])} where id = {pid};"
            )
        elif event["como"] == "agente":
            out.append(
                "insert into public.prospecto_notas (prospecto_id, cuerpo) "
                f"values ({pid}, {_lit(event['cuerpo'])});"
            )
        else:
            out.append(
                "insert into public.prospecto_notas (prospecto_id, cuerpo, autor) "
                f"values ({pid}, {_lit(event['cuerpo'])}, {_lit(event['autor'])});"
            )
        if event["como"] == "agente":
            out.append("reset role;")
            out.append("select set_config('request.jwt.claims', '', true);")
        out.append("")
    out += ["commit;", ""]
    return "\n".join(out)


if __name__ == "__main__":
    SEED_SQL.write_text(build_sql(read_seed()), encoding="utf-8")
    print(f"wrote {SEED_SQL.relative_to(ROOT)}")
